CLDN-2416 Fix docker build

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -70,13 +70,22 @@ jobs:
         inputs:
           targetType: 'inline'
           script: |
+            cd $(Build.SourcesDirectory)/core/docker
+            chmod +x ./build.sh
+            ./build.sh -a amd64
+            if [ $? -ne 0 ]; then
+            echo "Docker build failed"
+            exit 1
+            fi
             cd $(Build.SourcesDirectory)
             DOCKERFILE="FROM trino:${TRINO_VERSION}-amd64
             LABEL cccs.trino.upstream.version=${TRINO_VERSION}"
             DOCKERFILE_PATH=$(mktemp -d)/Dockerfile
             echo "${DOCKERFILE}" > "${DOCKERFILE_PATH}"
             echo "##vso[task.setvariable variable=DOCKERFILE_PATH]$DOCKERFILE_PATH"
-        displayName: Create Trino Docker File
+            echo "DOCKERFILE:"
+            echo "${DOCKERFILE}"
+        displayName: Docker build
       - task: Docker@2
         displayName: Login to ${{ variables.containerRegistry }}
         inputs:
