Fix broken build and push docker job

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -32,10 +32,13 @@ jobs:
     steps:
       - bash: |
           BRANCH_NAME=$(echo "$SYSTEM_PULLREQUEST_SOURCEBRANCH $BUILD_SOURCEBRANCH" | sed -r 's/^\s*(refs\/heads\/)?(\S*).*$/\2/' | sed 's/\//_/g')
-          echo "##vso[task.setvariable variable=BRANCH_NAME]$BRANCH_NAME"
+          echo "##vso[task.setvariable variable=BRANCH_NAME isOutput=true]$BRANCH_NAME"
+
         displayName: Parse Source Control Branch Name
       - bash: |
           $(Build.SourcesDirectory)/mvnw clean install -e -DskipTests -pl '!:trino-docs' -Dmaven.repo.local=${{ variables.m2RepoContainerPath }}
+          TRINO_VERSION=$(./mvnw --quiet help:evaluate -Dexpression=project.version -DforceStdout)
+          echo "##vso[task.setvariable variable=TRINO_VERSION isOutput=true]$TRINO_VERSION"
         displayName: Maven build
   - job: DockerBuildnPush
     dependsOn: ContainerBuild
@@ -44,6 +47,7 @@ jobs:
       containerRegistry: uchimera
       imageRepository: cccs/trino-base
       buildTimestamp: $[format('{0:yyyyMMddHHmmss}', pipeline.startTime)]
+      m2RepoContainerPath: /tmp/m2/repository
       DOCKER_BUILDKIT: 1
     container:
       image: uchimera.azurecr.io/cccs/dev/projector-intellij-ce:feature_update-to-431-mmrouet_20231031183145_b8080
@@ -52,22 +56,22 @@ jobs:
         - "${{ variables.m2RepoNodePath }}:${{ variables.m2RepoContainerPath }}"
       endpoint: uchimera
     steps:
+#      - bash: |
+#          BRANCH_NAME=$(echo "$SYSTEM_PULLREQUEST_SOURCEBRANCH $BUILD_SOURCEBRANCH" | sed -r 's/^\s*(refs\/heads\/)?(\S*).*$/\2/' | sed 's/\//_/g')
+#          echo "##vso[task.setvariable variable=BRANCH_NAME]$BRANCH_NAME"
+#        displayName: Parse Source Control Branch Name
       - bash: |
-          BRANCH_NAME=$(echo "$SYSTEM_PULLREQUEST_SOURCEBRANCH $BUILD_SOURCEBRANCH" | sed -r 's/^\s*(refs\/heads\/)?(\S*).*$/\2/' | sed 's/\//_/g')
-          echo "##vso[task.setvariable variable=BRANCH_NAME]$BRANCH_NAME"
-        displayName: Parse Source Control Branch Name
-      - bash: |
-          cd $(Build.SourcesDirectory)/core/docker
-          chmod +x ./build.sh
-          ./build.sh -a amd64
-          if [ $? -ne 0 ]; then
-            echo "Docker build failed"
-            exit 1
-          fi
+#          cd $(Build.SourcesDirectory)/core/docker
+#          chmod +x ./build.sh
+#          ./build.sh -a amd64
+#          if [ $? -ne 0 ]; then
+#            echo "Docker build failed"
+#            exit 1
+#          fi
           cd $(Build.SourcesDirectory)
-          TRINO_VERSION=$(./mvnw --quiet help:evaluate -Dexpression=project.version -DforceStdout)
-          DOCKERFILE="FROM trino:${TRINO_VERSION}-amd64
-          LABEL cccs.trino.upstream.version=${TRINO_VERSION}"
+#          TRINO_VERSION=$(./mvnw --quiet help:evaluate -Dexpression=project.version -DforceStdout)
+          DOCKERFILE="FROM trino:$(TRINO_VERSION)-amd64
+          LABEL cccs.trino.upstream.version=$(TRINO_VERSION)"
           DOCKERFILE_PATH=$(mktemp -d)/Dockerfile
           echo "${DOCKERFILE}" > "${DOCKERFILE_PATH}"
           echo "##vso[task.setvariable variable=DOCKERFILE_PATH]$DOCKERFILE_PATH"
